2025-07-06 16:36:12,445 INFO    MainThread:37787 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/ayoub/Desktop/PhDCourses/courses/ML_classifier/BankTermPrediction/wandb/run-20250706_163612-ndrqdczc/logs/debug.log
2025-07-06 16:36:12,445 INFO    MainThread:37787 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/ayoub/Desktop/PhDCourses/courses/ML_classifier/BankTermPrediction/wandb/run-20250706_163612-ndrqdczc/logs/debug-internal.log
2025-07-06 16:36:12,445 INFO    MainThread:37787 [wandb_init.py:init():830] calling init triggers
2025-07-06 16:36:12,445 INFO    MainThread:37787 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'model_type': 'SVC', 'kernel': 'rbf', 'C': 1.0, 'gamma': 'scale', 'probability': True, 'class_weight': 'balanced', '_wandb': {}}
2025-07-06 16:36:12,445 INFO    MainThread:37787 [wandb_init.py:init():871] starting backend
2025-07-06 16:36:12,445 INFO    MainThread:37787 [wandb_init.py:init():874] sending inform_init request
2025-07-06 16:36:12,447 INFO    MainThread:37787 [wandb_init.py:init():882] backend started and connected
2025-07-06 16:36:12,456 INFO    MainThread:37787 [wandb_init.py:init():953] updated telemetry
2025-07-06 16:36:12,550 INFO    MainThread:37787 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-06 16:36:13,009 INFO    MainThread:37787 [wandb_init.py:init():1029] starting run threads in backend
2025-07-06 16:36:13,121 INFO    MainThread:37787 [wandb_run.py:_console_start():2458] atexit reg
2025-07-06 16:36:13,121 INFO    MainThread:37787 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-06 16:36:13,121 INFO    MainThread:37787 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-06 16:36:13,121 INFO    MainThread:37787 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-06 16:36:13,122 INFO    MainThread:37787 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-06 16:36:13,280 INFO    MsgRouterThr:37787 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
